dokan-dev/dokany

dokan/create.c

It was printing the number in hexadecimal, but appending 08X at the end.
Fixed to add 0x at the beginning, which probably was the intended
output.

Fix DbgPrint message for CreateDisposition

---

sys/create.c

1) I used  0.6.0 for while and had BSOD very often.
2) Than i patched according to advices from based on advice from https://code.google.com/p/dokan/issues/detail?id=229 adn with this i had no BSOD for almost year.
3) Now after upgrade to this version 0.7.1(because this one have subscribed 64bit drivers ) I got BSOD today again. It typically happen if u use intensive parallel reading/writing.

BSOD Bad_pool bug Changes 

---

dokan/mount.c
dokan/readme.txt

As reported in the mailing list, DokanUnmount called
DokanRemoveMountPoint with an extra character at the end. Fixed it, and
mention DokanRemoveMountPoint in the readme.txt, since is an exported
function in the public header and is necessary if you mount the file
system in a path, not a drive letter.

Fix DokanUnmount bug

---

dokan/dokan.h

The same header says 'Delete on when "cleanup" is called' on the DokanFileInfo
definition, and "you must delete the file in Cleanup". Also, this contradicts
the mirror application behaviour, where the file/directory deletion is done on
Cleanup, not CloseFile.

Amend contradictory DeleteFile comment in header

---

dokan/dokan.h

If someone forgets to #include windows.h before dokan.h is included, weird
errors appear. It is good practice for header files to be self-contained.

Include windows.h in the main dokan header file

---

dokan/dokan.h
dokan/dokan.vcxproj
dokan_control/dokan_control.vcxproj
dokan_fuse/src/fusemain.cpp
dokan_mirror/dokan_mirror.vcxproj

Tried the current v0.7.3-beta release and could not bind to the library because of mangling/decorated function names in the x86 version of the library. Hope that my changes ( - works on my machine ;-) - ) correspond to the usual/common approach to handle this kind of problem.
Had to change the additional dependencies in the project files for control and mirror in order to build complete solution on my machine, is this only a problem on my site?

Exported function names for x86/x64 library

---

dokan/create.c
dokan/setfile.c
dokan_fuse/src/docanfuse.cpp
dokan_fuse/src/fusemain.cpp

This is a fix for CreateFile with a SL_OPEN_TARGET_DIRECTORY flag, which should open the containing directory instead of the file itself.
This flag is used in the MoveFileEx WinAPI with the MOVEFILE_REPLACE_EXISTING flag, which opens the target file's containing directory before deleting the target file. Without the fix this API fails with "permission denied" because the target file is opened and cannot be deleted.
Now the git push command works via dokan!

MoveFileEx fix

---

dokan.sln
dokan/dokan.c
dokan/dokan.h
dokan_mirror/mirror.c
sys/close.c
sys/create.c
sys/device.c
sys/directory.c
sys/dokan.c
sys/dokan.h
sys/event.c
sys/notification.c
sys/public.h
sys/read.c
sys/security.c
sys/sys.vcxproj

* The timeout per device has been implemented. The DokanOptions has a new property Timeout (Milliseconds).
* Prevent thread termination if not enough resources
* Fix BSOD in security
@Liryna 
Please create a .Net Method ResetTimeout. The exported method exists since a longer time https://github.com/dokan-dev/dokany/blob/master/dokan/dokan.def#L13. This method can be executed inside of the callbacks, to extend the timeout of the current request.
Please add the new DokanOption.Timeout

Irp pending timeout issue

---

dokan/dokanc.h
dokan_mirror/mirror.c
dokan_np/dokannp.c

While the sprintf_s functions are supposed to protect from buffer overflows and other errors, they still raise an exception if the buffer is too small, so any debug string longer than 512 characters still crashes the program. In practice, this limit is exceeded very easily, for example, when [matching a file name with a length of MAX_PATH against itself](https://github.com/dokan-dev/dokany/blob/master/dokan/directory.c#L382).
Instead of just increasing the buffer size and/or using snprintf, I prefer to use a combination of _vscwprintf() and _malloca()/_freea(), which computes the final length and then calls either alloca() for strings below 1024 bytes or malloc() for longer ones. This makes sure the string always gets shown in full (well, except for the unlikely case of a malloc() …

Use _malloca() for debug strings to avoid buffer overflows

---

dokan_fuse/include/fuse_win.h
dokan_fuse/include/utils.h
dokan_fuse/src/fusemain.cpp

The original struct stat lacks members like st_blksize etc and uses atime/mtime/ctime, which can only have accuracy in seconds. What's more, the difference with the struct FUSE_STAT in DokanFUSE and struct stat in user program causes stack overflows. The new struct FUSE_STAT is ported from msys2 64bits, which is actually ported from cygwin 64bits. With this modification, users with msys/cygwin(64-bit)toolchains can compile their FUSE programs with DokanFUSE library directly without any more modification other than changing their header files. However, for other toolchains like MSVC,mingw and cygwin 32bits, you need to explicitly replace struct stat in your FUSE program to use struct FUSE_STAT from fuse_win.h. Because the implementation of stat.h varies from operating systems and …

use struct stat from cygwin as struct FUSE_STAT for better compatibility

---

dokan_control/dokan_control.vcxproj
dokan_control/dokanctl.c

In the registry there is a mix of services with paths starting with
%SystemRoot% and \SystemRoot\. For some reason when CreateService()
creates the service in our case %SystemRoot% gets converted to
\SystemRoot\ but it seems to work fine.
The paths to the mounter and driver are verified before attempting
installation and an error code is returned if they don't exist.

The path to the driver is now resolved from %SystemRoot% #101

---

sys/init.c

The existing code assumes that if one of `SymbolicLinkName` `DiskDeviceName` or `FileSystemDeviceName` fails allocation, then the subsequent allocations also failed and does not free them. This may not be the case, resulting in a memory leak.
Other failure paths also fail to free these items.
Note: Resubmission of [pull 107](https://github.com/dokan-dev/dokany/pull/107).

Remove potential memory leak in DokanCreateDiskDevice on allocation failure (resubmit)

---

dokan/create.c

See https://github.com/dokan-dev/dokany/commit/1039c0adcd413733399995df0169010d17c01dde for more information

Thread win32 error code now gets reset before the ZwCreateFile callback is called

---

dokan/flush.c
dokan/lock.c
dokan/security.c
dokan/setfile.c
dokan/volume.c
dokan/write.c

Addition to my previous PR. Handle STATUS_NOT_IMPLEMENTED exactly same as if the callback was not set in DokanOperations. Most of callbacks already can safely return it, this is intended to support for the rest.

Support STATUS_NOT_IMPLEMENTED as a possible result from callbacks

---

sys/timeout.c

If system goes into hibernation mode it can happen that DokanCheckKeepAlive remove the MountPoint by mistake.

support hibernation mode

---

dokan_fuse/src/fusemain.cpp

The value of `fuse_file_info::fh` was `(uint64_t)(-1)`(<-- default value) after `fuse_create`.

Fix:Saving fileinfo after file creation in fuse.

---

dokan_fuse/src/fuse_helpers.c
dokan_fuse/src/fuse_opt.c

gcc in msys2 always complains about implicit pointer conversions and treats them as errors.

remove some compiler complaints

---

dokan_fuse/include/fuse.h
dokan_fuse/include/fuse_common.h

We should use _WIN32 instead WIN32 in FUSE wrapper headers. _WIN32 is safer. 
And more importantly when using these wrapper headers to develop applications, WIN32 is not defined in` fuse.h#L13 `when in x64 platform. `fuse_win.h` needs to be included for later(`fuse.h#L448`) WIN32 being defined.

use _WIN32 in FUSE wrapper headers instead of WIN32

---

dokan_fuse/include/fuse_win.h
dokan_fuse/src/dokanfuse.cpp
dokan_fuse/src/dokanfuse.def
dokan_fuse/src/utils.cpp

Creating a new folder with explorer under a sub-folder of the mounted path shows it needs higher privileges.
If we fill it, it will work.
This pull request queries the privileges of the mount path, gives back to every request which occurs.
It was written based on mirror.c.

Fuse handles GetFileSecurity callbacks.

---

dokan/mount.c

Spotted this bug while hunting other issues.
This may have caused invalid input to DeleteVolumeMountPoint in the !IsMountPointDriveLetter case.

dokan: null-terminate string in unmount

---

dokan_fuse/src/fusemain.cpp

Instead of calling statfs with an empty string we now call statfs with
the root directory "/". This is in line with POSIX which requires the
path to be valid and existing (an empty path is not)
I removed the comment `// Why do we need path argument??`. The answer to the question is that, on a Unix system, the path is needed to determine which filesystem you want to get the information from, i.e. depending on where the path resides, you would get the information about the filesystem the file/dir is located on.
http://linux.die.net/man/2/statfs

Call statfs with root directory /

---

dokan_fuse/src/dokanfuse.cpp
dokan_fuse/src/fuse_helpers.c

In dokan_fuse debug output the filenames are now printed out using %ls
in order to be compliant with the C++ standard and thus make the
printing work when compiling with GCC/MingW (without the printing would stop after the first character, if the second byte is NULL)
MSVC will happily print a wide-character-string when using %s but will
fail to print out single-byte strings. *This has to be kept in mind
when printing out single-byte strings using wide-character fwprintf*.
MSVC14 supports defining _CRT_STDIO_ISO_WIDE_SPECIFIERS to bring their
format-string handling in line with the standards.
From what I have read, Microsoft's decision to be not in line with the standard was to simplify compiling the same code-base for both unicode- and non-unicode systems back in the days. They tried to …

dokan_fuse: Use %ls for wide-character debug-print

---

dokan_wix/Dokan_x64.wxs
dokan_wix/Dokan_x86.wxs

**Not yet tested, don't merge**
Due to some oddity, we need to specify a version that is one version
lower than the one we are actually searching for.
References: #260, #244, #187
Quoting WiX-documentation:
Important: When doing a locale-neutral search for a file, you must set
the MinVersion property to one revision number lower than the actual
version you want to search for.

dokan_wix: Fix KB3033929-check

---

dokan/create.c
sys/create.c
sys/fileinfo.c

These changes are primarily for changing the behavior of creating a file when SL_OPEN_TARGET_DIRECTORY.
This is to fix this bug https://github.com/dokan-dev/dokany/issues/249
Now when SL_OPEN_TARGET_DIRECTORY is specified, the driver creates the fcb for the parent dir of the file (instead of for the file itself).  Then it passes the original filename to the dll.  The dll then checks to see if the file exits.  Then the dll opens the parent dir o fthe file.  If the file did not exist but the dir opened successfully, then it sets info to FILE_DOES_NOT_EXIST and returns STATUS_SUCCESS.  Word seems to rely on that behavior.  
The changes also fix an fcb and ccb leak and a memory leak of eventContext when an oplock operation fails.  FsRtlOplockFsctrl() was the one observed failing.  Now when …

SL_OPEN_TARGET_DIRECTORY directory and fcb leak

---

sys/create.c

I moved the code down to fix the coverity issue with fileName and parentDir if the device is read-only.
Then I realized I should just merge it with the block below it.  Otherwise there is a redundant check for SL_OPEN_TARGET_DIRECTORY.

fix coverity issues with freeing fileName and parentDir when device is read-only

---

dokan/create.c
sys/create.c

This has to do with SL_OPEN_TARGET_DIRECTORY
Both the the code I added in the driver, and the code that was already there in dokan\create.c for getting the parent directory would turn a path like \foo.txt into an empty string when trying to get the parent directory.
This was preventing files in the root of the mirror fs from being renamed.
I fixed both of them to get \ in that case.
Also, I noticed that dokan\creat.c was returning STATUS_SUCCESS even if opening the parent dir failed.  It shouldn't do that.  It should return success if the parent can be opened but the child does not exist.  It shouldn't return success if the parent cannot be opened.

Fix rename in root dir

---

sys/create.c

I noticed this happening 
```
M:\ echo blah > foo.txt
M:\ del foo.txt
[hang]
```
The cmd window is hung.  The driver and mirror are still ok. 
If I disabled Windows Defender real-time scanning, it didn't happen.
When I fixed the leaks that happened because of leaving early from the failed oplock operation, I also "fixed" a non-leak in the case above it, where the the oplock is pending. In that case, the operation is registered as pending, and no additional freeing is necessary or desirable.
Here is the fix

should not free eventContext, ccb, or fcb if oplock is pending

---

sys/read.c
sys/write.c

when writing zero bytes, complete irp normally.  also when reading or… writing zero bytes set Irp->IoStatus.Information = 0
this is about https://github.com/dokan-dev/dokany/issues/299

fix for WriteFile() of length zero byes

---

sys/cleanup.c
sys/create.c
sys/directory.c
sys/flush.c

Found some error paths that were still lacking proper locks when reviewing the code for the third time.

sys: FCB unlock on some error paths

---

appveyor.yml

Upgrading all packages ensures that we are running the latest Cygwin.
Sometimes dependencies of packages are incorrect and dependant packages
are thus not upgraded automatically when they should be.
This makes the Appveyor build working again after the cmake-package in
Cygwin was upgraded a few days ago breaking our build. Closes #335.

Appveyor: Upgrade all Cygwin packages before build

---

sys/cleanup.c
sys/fileinfo.c
sys/write.c

Rearrange locking  so that the FCB lock is not held for `CcPurgeCacheSection`.
Quick fix - requires testing.

sys: Do not hold locks for CcPurgeCacheSection

---

sys/cleanup.c
sys/create.c
sys/directory.c
sys/dokan.h
sys/fileinfo.c
sys/fscontrol.c
sys/lock.c
sys/notification.c
sys/read.c
sys/volume.c
sys/write.c

* Go through all Flags access for FCBs and CCBs
* Use helpers for access
* Make modification of flags use atomic operations
* Locks need to be held for less time because they are not needed for flags anymore

Use atomic operations for FCB and CCB flags instead of locks

---

samples/dokan_mirror/mirror.c

STATUS_NOT_A_DIRECTORY should be returned if a file is being opened and the FILE_DIRECTORY_FILE option is used.
The problem with allowing this, is that if the file has previously been opened as a normal file, it will set the (shared) FCB as being a directory ([here](https://github.com/dokan-dev/dokany/blob/master/sys/create.c#L1360)). As such, further reads on the file will fail!

MirrorCreateFile - Reject when trying to open a file as a directory

---

sys/fscontrol.c

Need to return STATUS_INVALID_DEVICE_REQUEST, as described [here](https://msdn.microsoft.com/en-us/library/ff469604.aspx). This is a fix for #200

Return correct status for FSCTL_FILESYSTEM_GET_STATISTICS

---

appveyor.yml
build.bat
dokan_fuse/build.ps1

This set of commits fixes a few issues and decreases the time needed for a build.
Issues:
* command output was not appearing in log
* documentation push and Coverity Scan were run when using AppVeyor in one's private fork
* MSBuild output was not appearing in Messages tab in AppVeyor
The other part of the patches are some speed-ups. We cache downloaded packages to reduce load on the mirrors and decrease build-times. The individual speed-ups are not very big for some of the commits, because the cache is downloaded as a zip-archive at the beginning of the build as well and it does not matter which server you download from. There are some improvements underway from the AppVeyor side, so this might get faster in the future. Download-locations can be flaky though, so even without huge …

CI: AppVeyor speed-ups and enhancements

---

appveyor.yml

1. Check return code of external commands faa9485. We want to fail early if external commands fail. Thus we introduce a function that checks the $LASTERRORCODE and use it throughout the code. This makes failures much easier to spot because the failure is near the cause of the error. Motivation for this was a failing build where the [Cygwin-installation failed half-way-through due too a flaky mirror](https://ci.appveyor.com/project/Maxhy/dokany/build/1.0.1-823/job/f2t221q6qxrpvyyd#L196) and I spent quite some time wondering about the [why cmake was trying to use MSVC instead of GCC](https://ci.appveyor.com/project/Maxhy/dokany/build/1.0.1-823/job/f2t221q6qxrpvyyd#L4771.) Turned out that native Windows-cmake is in the path and thus got run instead.
2. Run `git clang-format` on pull-requests …

AppVeyor Enhancements: BSOD, clang-format, error-checking

---

dokan_fuse/CMakeLists.txt
dokan_fuse/build.ps1
dokan_fuse/pkg-config.pc.in

Don't merge yet. This needs further testing and input.
This fixes #338.
This generates a pkg-config-file that can be used as a drop-in "replacement" for libfuse, i.e.
```
$ pkg-config --libs --cflags fuse
```
will return the dokanfuse-flags.
I have only tested this on Debian Stretch. Thus, it is lacking testing on Windows. I would be happy if someone could test it on
- Cygwin
- MSYS2-Installer - MinGW-W64-32bit
- MSYS2-Installer - MinGW-W64-64bit
I currently do not have any working Windows-system at hand to test myself.
You can add `-DCMAKE_INSTALL_PREFIX="/tmp/usr/` to the cmake-invokation to define another prefix to avoid cluttering your global directories while testing. You can then use the  `PKG_CONFIG_PATH` environment-variable to point pkg-config to the right `lib/pkgconfig`-dir. …

dokan_fuse: Add libfuse-compatible pkg-config

---

appveyor.yml

The MSYS2-MINGW-CMake packaging (or one of its dependencies is missing a dependency
to libxml2) This breaks our build, see: https://ci.appveyor.com/project/Maxhy/dokany/build/1.0.1-27/job/ova2o24yyjh9i009#L4739.
How I troubleshooted this:
The error-message with libuv is a red herring. Nothing is wrong with libuv from what I can see and on my system stderr complains about zlib instead of libuv as it does on AppVeyor (both are installed). Running the executable from the GUI will produce the correct error message as a MessageBox.
This commit can be reverted once the bug is fixed:
Alexpux/MINGW-packages#1991

CI: Temporary fix for bug in MSYS2-MINGW-CMake

---

sys/cleanup.c

DokanDispatchCleanup() was calling CcFlushCache() without acquiring the
PagingIoResource exclusive lock. This was allowing concurrent calls to
CcFlushCache(), via e.g. DokanDispatchRead() and DokanDispatchClose(), for the
same file control block ultimately leading to a deadlock in CcFlushCache().
Please see below a dump of my windbg session for more concrete evidence:
2: kd> !locks
**** DUMP OF ALL RESOURCE OBJECTS ****
KD: Scanning for held locks...........
Resource @ 0xffffaa05cc7b46c0    Exclusively owned
Contention Count = 2
NumberOfSharedWaiters = 1
NumberOfExclusiveWaiters = 1
Threads: ffffaa05ca9df7c0-01<*> ffffaa05c93fc080-01
Threads Waiting On Exclusive Access:
ffffaa05c93fe080
Resource @ 0xffffaa05c9626400    Exclusively owned
Contention Count = 2
NumberOfSharedWaiters = 1 …

Fix deadlock in DokanDispatchCleanup().

---

appveyor.yml

This fixes a small issue where the script did not account for the case where
no C-files where modified in a PR and git-clang-format wrote a
.diff-file with the text "no modified files to format".
[Example-PR where it occurred](https://ci.appveyor.com/project/Maxhy/dokany/build/1.0.1-62/job/v9r38yu1ciowoqm6/messages)
Ideally clang-format would print messages like this to stderr. As a
workaround we are grepping for the message to filter it out.

CI: Don't write clang-format diff if no changes in C-files

---

dokan_fuse/dokan_fuse.vcxproj
dokan_wix/Dokan_x64.wxs
dokan_wix/Dokan_x86.wxs

**This is completely untested. I have never tried installing, nor have I tried using the generated PDB to debug anything. Please double-check and test.**
Create debugging symbols both for Release and Debug configuration of the
MSVC dokanfuse1.dll and ship them in the installer.
See #427.

WiX: Ship PDB-files for dokanfuse.dll

---

dokan/create.c

The DOKAN_OPEN_INFO struct is ref-counted in userspace while an opaque pointer
to it is also stored, though not dereferenced, in kernel space via the
EVENT_CONTEXT struct.
Ref-counting is needed to manage the lifetime of DOKAN_OPEN_INFO as Dokan uses
loosely synchronized worker threads in userspace to dispatch the actual file
system requests.
When the ref-count of the DOKAN_OPEN_INFO goes to 0, the DOKAN_OPEN_INFO
pointer gets free'd. However worker threads other than the thread doing the
free() could still observe a stale copy of the pointer in their EVENT_CONTEXT
struct which each worker thread has a unique instance of.
This changes the user-space library so that there is an extra indirection to
lookup DOKAN_OPEN_INFO pointers. Instead of directly dereferencing a
potentially stale …

Fix use-after-free in GetDokanOpenInfo().

---

sys/read.c

Forgotten free MDL in DokanCompleteRead. Add the DokanFreeMdl to fix. Fix for #442 .
I think this time should be correct. Please correct me if I messed up again.

Add DokanFreeMdl for read operation

---

appveyor.yml

This fixes two issues with on AppVeyor MSYS2. See the commit-msgs for detailed descriptions.
1. Build was failing due to the way we upgrade MSYS2
2. Pacman was unnecessarily re-installing already installed packages.

CI: MSYS2 fixes and improvements

---

dokan/write.c
sys/event.c

The root cause is because the dokan.sys will still return status_success when the corresponding IRP is not found cause by the user cancellation. With this fix, the driver will return status_cancelled and the dokan usermode dll will handle the status returned correctly. This fix will fix the issue #447 .
Sorry for the typo in the previous pull request.

Fix crash issue cause by canceling the copy operation

---

appveyor.yml

Turns out that waiting for 60mins was not so smart... 😊 
Using the changes below, builds should fail early and we can find out, whether the build-VM does not shut down or whether it does not come back after reboot.
Instead of waiting for an hour to reboot, try rebooting in two different
ways with a timeout of 4 minutes each. If the system has not rebooted
after those two tries, fail the build.

CI: Try rebooting two times and reduce timeout

---

sys/cleanup.c
sys/create.c
sys/dokan.h
sys/fileinfo.c

The check of the filename is now implemented. It's suboptimal because the backslash should be added to the folder before the check is performed. This is not possible without allocation of additional memory. Anyway the changes improve the code a lot and code redundancy is eliminated.

Use filename check before doing flush. Remove code redudancy

---

dokan_fuse/include/fusemain.h
dokan_fuse/src/dokanfuse.cpp
dokan_fuse/src/fusemain.cpp

When fuse bindings calls the filler which is the dokans walk_directory method. The walk_directory is called on different thread. We need to ensure that even then the fuse context is set. This fixes one part of the issue https://github.com/dokan-dev/dokany/issues/465. The other changes are inside of fuse-bindings required.

Ensure fuse context is set during walk directory

---

dokan_fuse/include/fusemain.h
dokan_fuse/src/fusemain.cpp

Fixes #270.
Two remaining questions before merging. The first one is more out of interest, the second one is more relevant to this PR.
1. @Liryna As you can see I put the check earlier than you suggested in #270, which is in line with [what I read about file-deletion on Windows](http://download.microsoft.com/download/4/3/8/43889780-8d45-4b2e-9d3a-c696a890309f/File%20System%20Behavior%20Overview.pdf). This is a general question about Windows: What happens when the deletion fails during cleanup? Is it true that there is no possibility to signal user space that a deletion failed?
2. Is there the possibility of race conditions?
* FileSetDisposition is called
* the DeleteDirectory callback enumerates the direntries, finds none
* a file is placed into the directory
* DeleteDirectory returns …

FUSE: Check for non-empty directories on delete

---

samples/dokan_mirror/mirror.c
sys/create.c

For issue #490: FILE_NAMED_STREAMS flag 
set FILE_NAMED_STREAMS in FileSystemFlags  MirrorGetVolumeInformation() in mirror.c.
Do not append slash to path in front of filename if filename is a stream (DokanDispatchCreate() in create.c).
Also, do not prepend path (\) in front of filename if file is really an alternate data stream of the root directory.

Streams flag

---

samples/dokan_mirror/mirror.c

For some cases, the GetUserObjectSecurity function will return success but not set the output parameter LengthNeeded. This fix ensure the length is well set.
This fix would fix part of the issue on #476 and save the file correctly. Re-implement #507, #509 to look more clean.

Ensure the Security Descriptor length is set in mirror

---

appveyor.yml
samples/mirror_test.ps1
scripts/install_wlk_ifstest.ps1
scripts/run_ifstest.ps1
sys/create.c

This was more work than expected, but here it is:
* add install-script install_wlk_ifstest.ps1 for installing the IFSTest part of WLK/HCK. Currently only Win8.1 and Win10 Anniversary versions are supported. Not really sure about backward/forward compatibility of installing them on other OSes, but I think nothing bad should happen except failing tests (see the source on how to support other version or change the conditions for choosing one version over the other)
* run IFSTest from mirror_test.ps1
* Make AppVeyor re-use the installer built in the All-"Configuration", run the tests using that installer on both Win2012R2 (8.1) and and Win2016 (10 Anniversary)
* Please note that the automatic BSOD analysis does not work at the moment on AppVeyor's Win2016 (VS-2017) image, because they forgot …

Run IFSTest on AppVeyor

---

sys/dokan.c
sys/dokan.h
sys/dokan_utility.c
sys/event.c
sys/sys.vcxproj
sys/sys.vcxproj.filters
sys/timeout.c

Adding a function for searching WCHAR in PUNICODE_STRING. This function avoid BSOD caused by the characteristics of unsigned type. Replace the similar searching implement in dokan/sys project with this new implemented function.
This will fix #549 . Fixed typo in #553 .

Fix BSOD during searching the backslash

---

samples/dokan_mirror/mirror.c

'FindClose()' is not being called under error condition

---

samples/dokan_mirror/mirror.c

By MS-FSCC 2.6 File Attributes, 0x00000000 in the FileAttributes field means that the file attributes for this file MUST NOT be changed when setting basic information for the file. However, we are just set FileAttributes with 0x0 previously and cause file attribute lost. Fix this bug with this commit.
This will fix #584 .

Fix SetFileAttributes implementation

---

samples/dokan_mirror/mirror.c

Add Impersonate Caller User Option for Security Enhancement. Previously implementation will always done all the operations with the mounted user access token. Adding option to use the caller access token to get the handle for completing the operations. This option requires admin right to work properly.
Can be fix the security holes mentioned in #575 when the `Impersonate Caller User Option` (require administrator right to mount) is used to mount.

Add Impersonate Option for Security Enhancement.

---

README.md

The first commit only splits long lines to 80 characters without any content changes. The second commit performs some minor typo fixes.

Minor fixes to README file

---

appveyor.yml
dokan_fuse/build.ps1
dokan_fuse/cmake/toolchain-i686-pc-cygwin.cmake

Cygwin64 can compile binaries for Cygwin32. Install the corresponding
cross-compiler and use it for compiling dokan_fuse.
This should save quite a bit of time spent downloading 32-bit Cygwin
updates on AppVeyor. It also makes live easier, because there is no
longer any need to install the 32-bit Cygwin in parallel to the 64-bit
one on local machines.

FUSE: cross-compile 32-bit Cygwin DLL from 64-bit

---

dokan_fuse/src/fuse_opt.c

Reverting commit bfccd62599ef80899929cbbdf7b8f0fc78f8f07b because it caused a crash in my fuse-nfs builds,
probably because the buffer size given to strncpy was wrong.
Why was this changed in the first place, the additional bound check
seams unnecessary, and it wasn't made sure the string would get null
terminated if it would ever somehow prevent an overflow. The only
way I see this could happen would be if the "opt" argument was changed
by a different thread in this tiny moment between strlen and strcpy,
if that's even possible, and even then, why would anyone ever do that,
an attacker would already have control over the program at that stage.

Undo commit bfccd62599ef80899929cbbdf7b8f0fc78f8f07b

---

dokan/dokan.h
dokan/dokani.h
dokan/list.h
dokan_fuse/include/fuse_win.h
dokan_fuse/src/dokanfuse.cpp
dokan_fuse/src/fuse_helpers.c
dokan_fuse/src/fusemain.cpp
dokan_fuse/src/utils.cpp
dokan_np/dokannp.c

This reverts commit 81eca07b348e55d391f357c137adaa8fd8f11dc0. See issue #703 for details.

Revert "Improve windows header include typo"

---

sys/dispatch.c

Fixes #293  .
Changes proposed in this pull request:
According to the information provided by the last one of #293.
https://www.osronline.com/showthread.cfm?link=287522
After making some changes to the code in the article, it successfully compiles and solves the problem. The problem of capitalization is solved, everything becomes normal; I have no problem testing on WIN10, I hope you can compile a driver as soon as possible, I need to use it recently.
The main change is to add a function that converts the name and then call the conversion function at the entry.

Fix: file name are uppercase when reparse point is used?

---

sys/notification.c

During reviewing the security fix for buffer overflow issue. I found the fix may cause other issue. The szMountPoint->length is used as string length but not byte length.
- Div sizeof(WCHAR) before comparing with MAX_PATH

sys - The szMountPoint->length should be the byte length.

---

CHANGELOG.md
dokan/dokan.c
dokan/dokanc.h

Made a change in dokan1.dll userspace library.
Fixes #787.
- Library - Use `DbgPrintW` instead of `DbgPrint` when printing wide characters
- Library - Add error check for `_vscprintf` and `vsprintf_s` in `DokanDbgPrint`, and `_vscwprintf` and `vswprintf_s` in `DokanDbgPrintW`

Library - Use DbgPrintW instead of DbgPrint when printing wide characters

---

dokan/dokan.h

where Unmounted() operation should reference Mounted() operation and not itself
In the documentation of the Unmounted() callback the corresponding _other_ method (Mounted()) is referenced.

Small documentation fix... 

---

appveyor.yml
dokan/dokan.vcxproj
dokan_control/dokan_control.vcxproj
dokan_fuse/dokan_fuse.vcxproj
dokan_np/dokan_np.vcxproj
samples/dokan_mirror/dokan_mirror.vcxproj
sys/sys.vcxproj
sys/sys.vcxproj.filters

- Update the used SDK + WDK to the one from Windows 10 version 1903. 
- This also updates the Visual Studio toolset version to VS2019 (v142).
- This disables SSE ISA extensions for the Windows 7 kernel drivers & the user-space tools, for compatibility with older machines.

Misc tooling + build settings updates.

---

CHANGELOG.md
dokan/dokan.h

Clarifies the documentation of the DokanNotify*-functions introduced with version 1.3.0 to prevent incorrect implementations like discussed in https://github.com/dokan-dev/dokan-dotnet/pull/236

Clarify documentation of dokan file-change notification functions

---

CHANGELOG.md
dokan/directory.c
dokan/fileinfo.h

The support for FileIdExtdBothDirectoryInformation is required when the target is mapped as a volume into docker containers.
- [x ] My code follows the style guidelines of this project
- [ n/a] I have made corresponding changes to the existing documentation
- [ x] My changes generate no new warnings
- [ x] I have updated the change log (Add/Change/Fix)
- [ n/a] I have cleaned up the commit history (use rebase and squash)
Problem:
When a dokan mountpoint is used to map a volume into a Docker container, there is a problem changing to a subdirectory below the mountpoint.
Steps to reproduce
1. A directory `c:\mytarget` with subdirectories `A` and `B`
2.  docker must be installed
3. `mirror.exe /r c:\mytarget /l c:\docker\volume /w /d /s`
4. `docker run -ti -v c:\docker\volume:c:\targetinside …

Kernel - Added support for FileIdExtdBothDirectoryInformation

---

dokan/directory.c
dokan/dokan.c
dokan/dokan.rc
dokan/dokanc.h
dokan/mount.c
dokan/timeout.c

This PR adds support for cross-compiling the `dokan` subproject with GCC and mingw32-w64.
Building with mingw32-w64 eliminates the dependency to the Visual Studio C++ Runtime and allows building on a Linux build server (all our projects - even those targetting Windows - are built on Linux).

Add support for compiling with GCC

---

dokan_fuse/src/fusemain.cpp

Fixes # .
When reading data with a large delay, the IRP times out, which will cause the file object to be accidentally released.
When reading data in multiple reads, due to the dependency on the file object (hndl-> get_name ()), uncontrollable pointer errors will result.
This question has also been asked before: https://github.com/dokan-dev/dokany/issues/734
I fixed this problem, and through actual testing, I found that there would be no more file reading problems, but I do n’t know if the data returned by read can still be received by the kernel and processed correctly when the file object is released. At least my application looks normal.
-Compare the code, only two lines of code changed
-
-

fix read file exception

---

dokan/dokan.c
dokan/dokan.h
dokan_np/dokannp.c
samples/dokan_memfs/main.cpp
samples/dokan_memfs/memfs.cpp
samples/dokan_memfs/memfs.h
samples/dokan_mirror/mirror.c
sys/create.c
sys/dokan.c
sys/dokan.h
sys/event.c
sys/fscontrol.c
sys/lock.c
sys/public.h

Fixes https://github.com/dokan-dev/dokan-dotnet/issues/250
I could not figure out how to pass down the setting, but this should nonetheless be a good new default behavior in my opinion.
- Add the option to enable disconnecting / unmounting a network drive from explorer directly

Allow disconnecting of network drives

---

dokan/create.c
dokan/directory.c
sys/create.c
sys/fileinfo.c

There is a small typo in dokan/create.c, dokan/directory.c, sys/create.c, sys/fileinfo.c.
Should read `specified` rather than `specifed`.

docs: fix simple typo, specifed -> specified

---

dokan/mount.c

Fixes #957.
- [] I have commented my code, particularly in hard-to-understand areas
I think it isn't a significant enough change for updating the change log or even a comment.
I think a rebase/squash isn't needed.  I did only one commit.
Using BSF_NOTIMEOUTIFNOTHUNG in the BroadcastSystemMessage that is done in DokanBroadcastLink after mounting to a drive letter could cause the BroadcastSystemMessage call to block long enough to cause the driver to timeout the fs.  This flag is not necessary so it was removed.
-
-
-

remove BSF_NOTIMEOUTIFNOTHUNG flag in BroadcastSystemMessage

---

dokan/dokan.c

Mitigates #953.
This PR reduces the problem that a recently mounted device is directly unmounted if certain AV software is installed in the OS.
This is done by implementing the comments made in #953 (basically a reduction of the desirered access rights for certain CreateFile calls). Since there is still an open discussion for a bigger change in the issue, this PR is not intended to close it, but to provide a short term fix.

Reduce desired access rights for loop device handle and keepalive handle

---

dokan_fuse/src/fusemain.cpp

Fixes # .
- use stbuf params in readdir callback, which can improve performance

feat: use stbuf in dokan_fuse readdir callback

---

dokan_fuse/include/utils.h
dokan_fuse/src/dokanfuse.cpp
dokan_fuse/src/utils.cpp

We've got an infinite loop problem in 'convert_char' function when the get_func fail, because the return value in size_t would never less than zero.
- Fix the infinite loop problem by changing several function's return type from size_t to int.
-

FUSE - Fix compare size_t to zero in fuse utils

---

appveyor.yml

This reverts commit f980bb2bfb504dcea7538af2587c23492ce63ef2.
MSYS2 is by now installed in the "Visual Studio 2019" image on AppVeyor.
Thus, we can simply update the existing installing like it was done
previously.
As a side effect, this also avoids exceeding AppVeyor's maximum cache
size, because substantially less data needs to be cached.
Fixes https://ci.appveyor.com/project/Maxhy/dokany/build/job/a1q24gl0irqga8ao#L3581 
```
Updating build cache...
Cache 'C:\dokan_ci_cache' - Zipping...Unable to save cache - skipping
Compressed cache item cannot exceed 1,048,576,000 bytes.
Build success
```
- [ x ] My code follows the style guidelines of this project
- [ x ] I have performed a self-review of my own code
- [ x ] I have commented my code, particularly in hard-to-understand areas
- [ x ] …

Revert "CI: Install MSYS2 on VS2019 image"

---

dokan_fuse/src/dokanfuse.def

When dynamic linking the dokanfuse library, the application would still looking for the dll named dokanfuse1.
Need update it in file dokanfuse.def.

FUSE - update library name in module definition

---

dokan/directory.c
dokan/dokan.h

Reverts #9eb4d15bc4c533b73dd718b3114c0be758f874d9
[I'm upgrading the Rust bindings to use ^2](https://github.com/dokan-dev/dokan-rust/issues/3). The high-level API always defines `FindFilesWithPattern`, with a default implementation returning `STATUS_NOT_IMPLEMENTED`. But the MemFS example was not working well. I discovered that a few months ago, this function was not allowed to return `STATUS_NOT_IMPLEMENTED` anymore. I find that's too bad.
After I tried for a long time to allow Rust to choose whether `FindFiles` and `FindFilesWithPattern` are defined, I finally moved to changing the C library's behavior. It gives back the ability to all functions to return `STATUS_NOT_IMPLEMENTED`. I believe this will be beneficial for other bindings as well.

Library - Allow FindFilesWithPattern to return STATUS_NOT_IMPLEMENTED

---

sys/public.h

- `DOKAN_LINK_INFORMATION` is not used anymore.

Library - Remove unused DOKAN_LINK_INFORMATION

---

dokan/fileinfo.c

Still upgrading the Rust bindings to 2.0.5...
[Compilation on MinGW32](https://ci.appveyor.com/project/Liryna/dokan-rust/builds/44926022/job/d66wdi8dnyf9tds7) produces these errors:
```
src/dokany/dokan\fileinfo.c: In function 'DokanEndDispatchFindStreams':
src/dokany/dokan\dokani.h:197:34: warning: implicit declaration of function 'offsetof' [-Wimplicit-function-declaration]
197 |   ((ioEvent)->EventResultSize >= offsetof(EVENT_INFORMATION, Buffer)           \
|                                  ^~~~~~~~
src/dokany/dokan\dokani.h:197:34: note: in definition of macro 'IOEVENT_RESULT_BUFFER_SIZE'
197 |   ((ioEvent)->EventResultSize >= offsetof(EVENT_INFORMATION, Buffer)           \
|                                  ^~~~~~~~
src/dokany/dokan\fileinfo.c:29:1: note: 'offsetof' is defined in …
```

Library - Fix build on MinGW32

---

dokan/dokan.c
dokan/dokan.def
dokan/dokan.h

Added two API functions `DokanRegisterWaitForFileSystemClosed` and `DokanUnregisterWaitForFileSystemClosed`, for registering and unregistering a callback to be called when the `DeviceClosedWaitHandle` is set. Makes it easier to register work to be done after dismount without letting a thread wait for it.
New feature.
-
-
-

Register callback for dismount

---

dokan_fuse/src/utils.cpp

`Int32x32To64` macro internally truncates the arguments to int32, while `time_t` is 64-bit on most/all modern platforms. Therefore, usage of this macro creates a Year 2038 bug.
I detailed this issue a while ago in a writeup, and spotted the same issue in this repository when updating the list of affected repositories:
<https://cookieplmonster.github.io/2022/02/17/year-2038-problem/>

utils: fix a Y2038 bug by replacing `Int32x32To64` with multiplication
