README.md
dokan/dokan.h
dokan/dokani.h
dokan/lock.c

Some statements were ambiguous and not really meaningful. I tried to be as accurate in representing what the comments would supposedly mean. 
I also worked heavily on the wiki, which is not part of this pull request.

Heavily redone comments

---

dokan.sln
dokan/dokan.c
dokan/dokan.h
dokan_mirror/mirror.c
sys/cleanup.c
sys/close.c
sys/create.c
sys/device.c
sys/directory.c
sys/dispatch.c
sys/dokan.c
sys/dokan.h
sys/event.c
sys/except.c
sys/fileinfo.c
sys/flush.c
sys/fscontrol.c
sys/lock.c
sys/notification.c
sys/public.h
sys/read.c
sys/security.c
sys/sys.vcxproj
sys/sys.vcxproj.filters
sys/volume.c
sys/write.c

Have now implemented the central error handling. This helps to make the driver stable and to keep some standards for each Irp. Next step would be to create IrpContext like fastfat and also to extend the exception handler.

Exception handling

---

dokan_fuse/include/fusemain.h
dokan_fuse/src/docanfuse.cpp
dokan_fuse/src/fusemain.cpp

Hi,
I have found a number of problems with the FUSE wrapper while trying to port my FUSE file system from *nix to Windows. Here's my attempt to fix them. Please, check commit messages for more information.
Sample use cases before
http://i.imgur.com/kDFPyPW.gifv
…and after
http://i.imgur.com/dcUGsAd.gifv
Best regards,
Dmitrii Toksaitov

Fix the Dokan FUSE library

---

dokan_control/dokanctl.c
sys/create.c
sys/device.c
sys/dokan.c
sys/dokan.h
sys/event.c
sys/fscontrol.c
sys/init.c
sys/notification.c
sys/pnp.c
sys/read.c
sys/timeout.c
sys/volume.c
sys/write.c

Change the way dokan does mounting to support SocketConnection

fix mounting to get SocketConnection work

---

dokan/directory.c
dokan/dokan.h

Small enhancement to FindFiles without breaking API compatibility.

Call FindFiles if FindFilesWithPattern returns STATUS_NOT_IMPLEMENTED

---

sys/create.c
sys/dokan.h
sys/fscontrol.c
sys/init.c
sys/read.c
sys/sys.vcxproj.filters

This should solve the remaining mounting issue and the redirector

fix mounting issue

---

sys/create.c
sys/init.c

This is a workaround for this issue.

Antivirus software tries to create files before we have some waiters

---

dokan_fuse/src/docanfuse.cpp

Trying to save a Microsoft Office Word file on DokanFuse drive isn't working.
In my case it writes a much bigger file. Like ~131 KB, but it should be around 11 KB.
It turned out that Word works like this on normal case:
- SetEndOfFileInformationFile (~131 KB)
- SetAllocationInformationFile (~131 KB)
- many WriteFile calls; writes the content which size is ~11 KB
- SetEndOfFileInformationFile (~11 KB); shrinks back the filesize to content's size
- SetAllocationInformationFile (~11 KB)
On the case of using DokanFuse the SetAllocationInformationFile's result is "NOT IMPLEMENTED", so it tries to
- SetEndOfFileInformationFile (~131KB) - OK
- SetAllocationInformationFile (~131KB) - NOT IMPLEMENTED
for a few times, then gives it up, and only write the files content, but not shrinks the filesize …

fix/saving MS Word files

---

sys/create.c

Fix for REFERENCE_BY_POINTER when NETWORK_DRIVE is used

networkdrive fileObject has no Vpb

---

README.md
dokan_wix/Bootstrapper/Bundle.wxs
dokan_wix/Dokan_x64.wxs
dokan_wix/Dokan_x86.wxs

On Windows 7 and 2008 R2 the installer did not check whether SP1 and KB3033929 are installed which led to confused users like me or #187 or #244. For details see the individual commits.
I will need to do some testing, to test the different combinations. ETA end of this week!

Installer: Make sure that all updates are installed on Win7

---

dokan_wix/Dokan_x64.wxs
dokan_wix/Dokan_x86.wxs

Minor fix for VS2015Redist 23918

---

sys/cleanup.c
sys/fileinfo.c
sys/flush.c
sys/fscontrol.c
sys/read.c
sys/write.c

@marinkobabic  said it looks ok now.
https://github.com/dokan-dev/dokany/issues/265

More fs rtl check oplock

---

dokan/dokan.c
dokan/timeout.c
sys/close.c
sys/create.c
sys/device.c
sys/directory.c
sys/dispatch.c
sys/dokan.c
sys/dokan.h
sys/event.c
sys/except.c
sys/fscontrol.c
sys/init.c
sys/notification.c
sys/pnp.c
sys/read.c
sys/security.c
sys/timeout.c
sys/volume.c
sys/write.c

Here you have the updated pull request which also works using the mountmanager.

Fix BSOD mount/unmount, BitDifender, symantec desktop encryption

---

dokan/dokan.h

New try. Hope it is beter this time.

Sync comments with dokan-dotnet and fix Doxygen issues

---

sys/cleanup.c
sys/close.c
sys/create.c
sys/device.c
sys/directory.c
sys/dokan.c
sys/dokan.h
sys/event.c
sys/fileinfo.c
sys/flush.c
sys/fscontrol.c
sys/lock.c
sys/notification.c
sys/read.c
sys/security.c
sys/write.c

This is unfortunately somewhat large.
Tested with copying deep filetrees with 80000+ files.
Related to:
https://github.com/dokan-dev/dokany/issues/318
https://github.com/keybase/client/issues/4018

Rewrite FCB locking

---

dokan_wix/Bootstrapper/Bundle.wxs

@Rondom suggests this check may be helpful in the bundle, not just the individual packages.

check for GDR/LDR version of KB3033929 in bundle

---

sys/dokan.c
sys/dokan.h

* No operational changes.
* Eliminate superfluous conditional
* Document some CCB field current locking practices
* Remote one dead field

sys small tidyup

---

sys/create.c

Fix for issue https://github.com/dokan-dev/dokany/issues/359. Please do a review if I'm doing the buffer copy correct. Maybe is there a much simpler way to compare the strings?
The issue is related to the dokan architecture. If we face more such problems in the future a generic approach must be implement to avoid such problems.

fix bsod issue related to filesystem mount on Windows 10 build 14936

---

sys/security.c

To prevent BSOD in situations like #366

Double check that the returned security descriptor is valid

---

README.md

I have tested Dokany on the final version of Windows Server 2016 running in a qemu-VM with SecureBoot enabled.

Add Windows 2016 support to README

---

samples/dokan_mirror/mirror.c

If mirror cannot get the SE_SECURITY_NAME privilege, don't ask for SACL in MirrorGetFileInformation. This will confuse win7 for some reason, as in #391.

Mirror: Return empty SACL if mirror doesn't have SeSecurityPrivilege

---

sys/security.c

This is so that it can easily be used with win32 functions without having to copy the security descriptor into a separate aligned buffer.

Align security descriptor to 4-byte boundary in DokanDispatchSetSecurity

---

sys/cleanup.c
sys/create.c
sys/dokan.h
sys/fileinfo.c
sys/flush.c
sys/fscontrol.c
sys/lock.c
sys/read.c
sys/write.c

This makes locking less wide with especial care to FsRtl locking routines.
Will do testing on monday.

sys: Less wide locking

---

appveyor.yml

Revert "CI: Temporary fix for bug in MSYS2-MINGW-CMake"

---

sys/fileinfo.c

Networkdrive has no slash root folder. The diskdevicename must be returned in this case

Fix BSOD. When drive ist started using n option and procmon is attaced

---

sys/fileinfo.c

pass absolute path to mirror for renaming

fix relative path rename

---

sys/create.c
sys/directory.c
sys/fileinfo.c

Fix here described issue https://github.com/dokan-dev/dokany/issues/436

Flush any opened files before doing a rename

---

sys/fileinfo.c

Before rename the targetObject should be flushed as well

flush the targetObject as first and then the source file

---

dokan_fuse/src/dokanfuse.cpp
dokan_fuse/src/fusemain.cpp

[Recent changes introduced some warnings during compilation](https://ci.appveyor.com/project/Maxhy/dokany/build/1.0.3-172/job/ofn54l9mo9lpqxe6#L5222). Fix them.

FUSE: Fix GCC-warnings

---

samples/dokan_mirror/mirror.c
sys/create.c

Fix for issue 502 in driver
Fix for issue 503 in mirror

Issue 502 503

---

samples/dokan_mirror/mirror.c

Fix typo in recent commit

---

sys/dokan.c

See https://www.greyhathacker.net/?p=818

Prevent BSOD if output buffer address is not in user space

---

sys/dokan.c

Revert "Prevent BSOD if output buffer address is not in user space"

---

sys/device.c

This should resolve the hang mentioned in #554 . Dokany has a few incorrect bounds checks. I am submitting this PR to get a build that I can verify the issue is resolved in.

Resolve hang described in issue #554

---

samples/mirror_test.ps1

This should make testing more robust because if you only run the tests once and the directory was empty before you can be sure that no test affects the other due to files that could not be deleted because they were still in use for some reason, for example.
Using the different "names" / dirs we can distinguish between different runs as well and thus do statistics over which test cases pass/fail in which configuration.
Please double-check the code to make sure that I have not missed something.

mirror_test: Use separate dirs for each config

---

dokan/dokan.c
dokan/dokanc.h
sys/device.c
sys/dokan.h
sys/event.c
sys/fscontrol.c
sys/init.c
sys/notification.c
sys/public.h
sys/timeout.c

The following issues should be fixed
https://github.com/dokan-dev/dokany/issues/517
https://github.com/dokan-dev/dokany/issues/332
and the following one may also work properly for session drives
https://github.com/dokan-dev/dokany/issues/312

Fix current session issues

---

documentations/mainpage.md

Fixed grammar, removed personal references

---

dokan/dokan.h

Addresses #587.
Note that the intention of line 743 was not clear, so that sentence was not fully fixed.

fixed typos and grammar, removed references to 'you'

---

dokan_wix/Dokan_x64.wxs
dokan_wix/Dokan_x86.wxs

added dokan_vector.h to both x86 and x64 installs

add dokan_vector.h to installed header files

---

CHANGELOG.md
cert/dokan-import.ps1

Fixes #589  .
-Updated dokan-import.ps1 to check if running as admin and relaunch if not. Also wraps existing function in a check for secureboot being enabled.
First Pull request so hope I did this right.

Fix cert manager

---

dokan_fuse/include/dokanfuse.h
dokan_fuse/src/dokanfuse.cpp

Add allocation unit size and sector size as options in dokany fuse wrapper

expose allocation unit size and sector size to FUSE

---

samples/dokan_mirror/mirror.c

- Gets disk free space in mirror

mirror - Get disk free space

---

CHANGELOG.md
dokan/dokan.vcxproj
dokan_control/dokan_control.vcxproj
dokan_fuse/dokan_fuse.vcxproj
dokan_np/dokan_np.vcxproj
samples/dokan_mirror/dokan_mirror.vcxproj
sys/sys.vcxproj

Fixes #837.
- Enable Code Analysis warnings for all debug configurations
- (cannot say "my changes generate no new warnings", because the entire point is that it exposes warnings that should already be generated)

Enable code analysis for all debug configurations in Visual Studio

---

dokan_fuse/include/utils.h
dokan_fuse/src/dokanfuse.cpp
dokan_fuse/src/utils.cpp

Fixes # .issue 893 Fix up dokanfuse mount error when chinese mount path.
-
-
-

Description:Fix up dokanfuse mount error when chinese mount path.

---

sys/device.c

Fixes #355 . 
Compared with opening the properties of windows local drive's sub-directories, I found the IOCTL_MOUNTDEV_QUERY_DEVICE_NAME return STATUS_INVALID_PARAMETER, while the dokan mirror drive's sub-dir return SUCCESS.
- add IsVolumeOpen check and return STATUS_INVALID_PARAMETER in the MOUNTDEVCONTROLTYPE.
-

Kernel - Fix subfolder property when using mount manager

---

samples/dokan_memfs/memfs_operations.cpp

Fixes issue that `SetFileAttributes(..., FILE_ATTRIBUTE_NORMAL)` can
clean attributes prohibited to clean, for example, `FILE_ATTRIBUTE_DIRECTORY` .
See [SetFileAttributesW documentation](https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-setfileattributesw).
- Operate on allowed attributes only
- Remove incorrect behavior in case `fileattributes == 0`
- Rework incorrect condition `(fileattributes & (fileattributes - 1))`

Fix SetFileAttributes behavior for memfs sample

---

.gitignore
README.md
chocolatey/dokany.nuspec.template
chocolatey/package.ps1
chocolatey/release.ps1
chocolatey/tools/chocolateyinstall.ps1.template

Fixes #574
- build a chocolatey package
- a script to publish chocolatey package
The publishing script might need to be run from its directory.
The publishing script requires `CHOCO_API_KEY` environment variable to be set. I created a user [`dokan-dev`](https://community.chocolatey.org/profiles/dokan-dev) on Chocolatey and can transfer credentials as soon as dokan-dev is ready to take over. The test package generated with the scripts is already approved and out there.

Chocolatey package
